default_platform(:ios)

platform :ios do

  before_all do
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"
  end

  desc "Load ASC API Key information to use in subsequent lanes"
  lane :load_asc_api_key do
   app_store_connect_api_key(
     key_id: ENV["ASC_KEY_ID"],
     issuer_id: ENV["ASC_ISSUER_ID"],
     key_content: ENV["ASC_KEY"],
     in_house: false # detecting this via ASC private key not currently supported
   )
  end

  desc "List Provisioning Profiles" 
  lane :list_profiles do
    sh "security find-identity -v -p codesigning" 
  end

  desc "Build and upload to TestFlight"
    lane :build_upload_testflight do
      load_asc_api_key
      setup_ci
      match(
        type: 'appstore',
        readonly: false,
        verbose: true,
        force: true,
        git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"]
      )
      list_profiles
      sync_code_signing(
        type: "appstore",
        readonly: true
      )
      
      project_path = Dir.glob("*.xcodeproj").first
      # Автоматически получаем bundle identifier из Info.plist
      info_plist_path = "Teletester/GoogleService-Info.plist"
      app_bundle_id = get_info_plist_value(path: "./Info.plist", key: "CFBundleIdentifier")
      # Получаем code_sign_identity автоматически
      code_sign_identity = sh("security find-identity -v -p codesigning | grep 'Apple Distribution' | head -n 1 | awk '{print $2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30,$31,$32,$33,$34,$35,$36,$37,$38,$39,$40,$41,$42,$43,$44,$45,$46,$47,$48,$49,$50}'").strip
      update_code_signing_settings(
        use_automatic_signing: false,
        path: project_path,
        team_id: ENV["TEAM_ID"],
        bundle_identifier: app_bundle_id,
        code_sign_identity: code_sign_identity,
        sdk: "iphoneos*",
        profile_name: "match AppStore #{app_bundle_id}"
      )
      build_app(
        scheme: "Teletester",
        xcargs: "-allowProvisioningUpdates",
        export_team_id: ENV["TEAM_ID"],
        verbose: true
      )
      upload_to_testflight(skip_waiting_for_build_processing: true)
   end
end