default_platform(:ios)

platform :ios do

  before_all do
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"
  end

  desc "Load ASC API Key information to use in subsequent lanes"
  lane :load_asc_api_key do
   app_store_connect_api_key(
     key_id: ENV["ASC_KEY_ID"],
     issuer_id: ENV["ASC_ISSUER_ID"],
     key_content: ENV["ASC_KEY"],
     in_house: false # detecting this via ASC private key not currently supported
   )
  end

  desc "List Provisioning Profiles" 
  lane :list_profiles do
    sh "security find-identity -v -p codesigning" 
  end

  desc "Build and upload to TestFlight"
    lane :build_upload_testflight do
        # Основная версия задаётся вручную через переменную MAJOR_VERSION
        major_version = ENV["MAJOR_VERSION"] || "1.0"
        last_uploaded_build = (ENV["LAST_UPLOADED_BUILD_NUMBER"] || "0").to_i
        new_minor = last_uploaded_build + 1
        new_build_number = "#{major_version}.#{new_minor}"
        increment_build_number(build_number: new_build_number)
      load_asc_api_key
      setup_ci
      match(
        type: 'appstore',
        readonly: false,
        verbose: true,
        force: true,
        git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"]
      )
      list_profiles
      sync_code_signing(
        type: "appstore",
        readonly: true
      )
      
      project_path = Dir.glob("*.xcodeproj").first
      UI.important "Dir.glob: #{Dir.glob("*.xcodeproj")}"
      UI.important "Project path: #{project_path}"
      target_name = File.basename(project_path, '.xcodeproj')
      unless target_name && !target_name.empty?
        UI.user_error!("Target name could not be determined from project path: #{project_path}")
      end
      code_sign_identity = sh("security find-identity -v -p codesigning | grep 'Apple Distribution' | head -n 1 | awk -F '\"' '{print $2}'").strip
      update_code_signing_settings(
        use_automatic_signing: false,
        path: project_path,
        team_id: ENV["TEAM_ID"],
        bundle_identifier: ENV["BUNDLE_IDENTIFIER"],
        code_sign_identity: code_sign_identity,
        sdk: "iphoneos*",
        profile_name: "match AppStore #{ENV["BUNDLE_IDENTIFIER"]}",        
      )      
      build_app(
        scheme: target_name,
        xcargs: "-allowProvisioningUpdates",
        export_team_id: ENV["TEAM_ID"],
        verbose: true
      )
      upload_to_testflight(skip_waiting_for_build_processing: true)      
      sh("echo 'LAST_UPLOADED_BUILD_NUMBER=#{new_build_number}' >> $GITHUB_ENV")
   end
end