default_platform(:ios)

platform :ios do

  before_all do
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"
  end

  desc "Load ASC API Key information to use in subsequent lanes"
  lane :load_asc_api_key do
   app_store_connect_api_key(
     key_id: ENV["ASC_KEY_ID"],
     issuer_id: ENV["ASC_ISSUER_ID"],
     key_content: ENV["ASC_KEY"],
     in_house: false # detecting this via ASC private key not currently supported
   )
  end

  desc "List Provisioning Profiles" 
  lane :list_profiles do
    sh "security find-identity -v -p codesigning" 
  end

  desc "Build and upload to TestFlight"
    lane :build_upload_testflight do
      load_asc_api_key
      setup_ci          
      match(type: 'appstore',
            readonly: false,
            verbose: true,
            force: true,
            git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"])
      list_profiles
      sync_code_signing(
        type: "appstore", # or "development", "adhoc", "enterprise"
        readonly: true)
      build_app(
        scheme: "Teletester",
        xcargs: "-allowProvisioningUpdates",
        export_team_id: "C6US6NYK48",
        verbose: true
      )
      upload_to_testflight
   end
end