name: unity-ios-upload

description: >
  This workflow uploads the iOS build artifact to TestFlight using Fastlane, downloading the build artifact from the main build workflow.


on:
  workflow_dispatch:
    inputs:
      artifact_url:
        description: 'Direct URL to the iOS build artifact (zip, etc.)'
        required: true

jobs:
  xcodeBuildAndUpload:
    runs-on: macos-latest
    env:
      IOS_BUILD_PATH: ${{ format('{0}/build/iOS', github.workspace) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download iOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.inputs.artifact_name }}
          path: build/iOS

      - name: List downloaded files
        run: ls -R build

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ vars.XCODE_VERSION || '16.3.0' }}
      
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1.269.0
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Generate MATCH_GIT_BASIC_AUTHORIZATION
        run: |
          echo -n "NikDyr:${GH_PAT}" | base64 > base64.txt
          echo "MATCH_GIT_BASIC_AUTHORIZATION=$(cat base64.txt)" >> $GITHUB_ENV
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
      
      - name: Build & upload iOS binary
        run: bundle exec fastlane ios build_upload_testflight
        env:
          ASC_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          ASC_KEY: ${{ secrets.APPSTORE_P8 }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ env.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          TEAM_ID: ${{ vars.APPLE_TEAM_ID }}
          BUNDLE_IDENTIFIER: ${{ vars.BUNDLE_IDENTIFIER }}
          MATCH_GIT_URL: ${{ vars.MATCH_GIT_URL }}
          LAST_UPLOADED_BUILD_NUMBER: ${{ vars.LAST_UPLOADED_BUILD_NUMBER }}
          XC_TARGET_NAME: "Unity-iPhone"
