name: Download Artifact From Another Workflow

on:
  workflow_dispatch:

jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact from another workflow
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: unity_ios.yml # например, build.yml
          name: Build-iOS        # имя артефакта, который был сохранён
          path: ./artifact           # куда скачать

      - name: List artifact contents
        run: ls -la ./artifact

      - name: Do something with artifact
        run: |
          # Ваши действия с ./artifact
          echo "Processing artifact..."